# Generated by Django 4.2.29 on 2026-03-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_company_options_company_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='account_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='company',
            name='authorized_signatory',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='declaration',
            field=models.TextField(blank=True, default='Goods once sold will not be taken back or exchange.\nWe declare that this invoice shows the actual price of\nthe goods described and that all particulars are true and\ncorrect.'),
        ),
        migrations.AddField(
            model_name='company',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='pan_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
