# Generated by Django 4.2.29 on 2026-03-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auditlog_updated_at_customer_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('PLATFORM_OWNER', 'Platform Owner'), ('COMPANY_OWNER', 'Company Owner'), ('STAFF', 'Staff')], default='STAFF', max_length=20),
        ),
    ]
